apiVersion: azure.jet.crossplane.io/v1alpha1
kind: ResourceGroup
metadata:
  name: example
spec:
  forProvider:
    location: "East US"
    tags:
      provisioner: crossplane
  providerConfigRef:
    name: example