apiVersion: dbformariadb.azure.jet.crossplane.io/v1alpha2
kind: FirewallRule
metadata:
  name: example-mariadb-fw-rule
spec:
  forProvider:
    endIpAddress: 40.112.8.12
    resourceGroupNameRef:
      name: example
    serverName: test-server
    startIpAddress: 40.112.8.12
  providerConfigRef:
    name: default
