apiVersion: dbformariadb.azure.jet.crossplane.io/v1alpha2
kind: VirtualNetworkRule
metadata:
  name: example-mariadb-vnet-rule
spec:
  forProvider:
    resourceGroupNameRef:
      name: example
    serverName: example-mariadb-server
    subnetIdRef:
      name: example
  providerConfigRef:
    name: default
