apiVersion: dbformariadb.azure.jet.crossplane.io/v1alpha2
kind: Database
metadata:
  name: examplemariadbdatabase
spec:
  forProvider:
    charset: utf8
    collation: utf8_general_ci
    resourceGroupNameRef:
      name: example
    serverName: example-mariadb-server
  providerConfigRef:
    name: default
