apiVersion: postgresql.azure.jet.crossplane.io/v1alpha1
kind: FlexibleServerConfiguration
metadata:
  name: example-flexible-psql-configuration
spec:
  forProvider:
    name: backslash_quote
    serverIdRef:
      name: example-flexible-psqlserver
    value: "on"
  providerConfigRef:
    name: example
