apiVersion: postgresql.azure.tf.crossplane.io/v1alpha1
kind: PostgresqlServer
metadata:
  name: example
spec:
  forProvider:
    name: example-psqlserver
    resourceGroupNameRef:
      name: example-rg
    location: "East US"
    administratorLogin: "psqladminun"
    administratorLoginPasswordSecretRef:
      name: psql-password
      namespace: crossplane-system
      key: password
    skuName: "GP_Gen5_4"
    version: "9.6"
    storageMb: 640000
    publicNetworkAccessEnabled: true
    sslEnforcementEnabled: true
    sslMinimalTlsVersionEnforced: "TLS1_2"
  providerConfigRef:
    name: example