apiVersion: postgresql.azure.tf.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: example-psql-configuration
  annotations:
    crossplane.io/external-name: array_nulls
spec:
  forProvider:
    resourceGroupNameRef:
      name: example
    serverNameRef:
      name: example-psqlserver
    value: "off"
  providerConfigRef:
    name: example