apiVersion: cache.azure.jet.crossplane.io/v1alpha1
kind: EnterpriseDatabase
metadata:
  name: default
spec:
  forProvider:
    resourceGroupNameRef:
      name: example
    clusterIdRef:
      name: example-redis-enterprise-cluster
  writeConnectionSecretToRef:
    name: conn-example-redis-enterprise-database
    namespace: crossplane-system
  providerConfigRef:
    name: example