apiVersion: redis.azure.jet.crossplane.io/v1alpha1
kind: FirewallRule
metadata:
  name: examplerule
spec:
  forProvider:
    redisCacheNameRef:
      name: example-redis
    resourceGroupNameRef:
      name: example
    startIp: "1.2.3.4"
    endIp: "2.3.4.5"
  providerConfigRef:
    name: example