apiVersion: storage.azure.jet.crossplane.io/v1alpha1
kind: Blob
metadata:
  name: example
  annotations:
    crossplane.io/external-name: sample_content
spec:
  forProvider:
    type: Block
    sourceContent: inline contents of this blob
    storageAccountNameRef:
      name: example
    storageContainerNameRef:
      name: example
  providerConfigRef:
    name: example
