apiVersion: storage.azure.tf.crossplane.io/v1alpha1
kind: Account
metadata:
  name: example-storage-account
  annotations:
    crossplane.io/external-name: crossplaneexamplestoracc
spec:
  forProvider:
    resourceGroupNameRef:
      name: example
    location: "East US"
    accountTier: "Standard"
    accountReplicationType: "LRS"
    tags:
      provisioner: crossplane
  providerConfigRef:
    name: example