apiVersion: network.azure.tf.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  name: example-lb
spec:
  forProvider:
    location: East US
    resourceGroupNameRef:
      name: example
  providerConfigRef:
    name: example