apiVersion: network.azure.jet.crossplane.io/v1alpha2
kind: PublicIP
metadata:
  name: example
spec:
  forProvider:
    allocationMethod: Static
    location: West Europe
    resourceGroupNameRef:
      name: example
    tags:
      environment: Production
  providerConfigRef:
    name: default
