apiVersion: eventhub.azure.jet.crossplane.io/v1alpha2
kind: Namespace
metadata:
  name: example1
spec:
  forProvider:
    capacity: 2
    location: West Europe
    name: example-namespace
    resourceGroupNameRef:
      name: example
    sku: Standard
    tags:
      environment: Production
  providerConfigRef:
    name: example
