apiVersion: sql.azure.tf.crossplane.io/v1alpha1
kind: Server
metadata:
  name: example-mssqlserver
spec:
  forProvider:
    location: "East US"
    version: "12.0"
    administratorLogin: "mssqladminun"
    administratorLoginPasswordSecretRef:
      name: mssql-password
      namespace: crossplane-system
      key: password
    resourceGroupNameRef:
      name: example
    tags:
      provisioner: crossplane
  providerConfigRef:
    name: example
